/**
 * DON'T EDIT THIS FILE WHICH WAS GENERATED BY './scripts/generate-configs.js'.
 */
"use strict"

module.exports = {
    "+angular": require("./configs/+angular"),
    "+browser": require("./configs/+browser"),
    "+eslint-plugin": require("./configs/+eslint-plugin"),
    "+modules": require("./configs/+modules"),
    "+node": require("./configs/+node"),
    "es2015": require("./configs/es2015"),
    "es2016": require("./configs/es2016"),
    "es2017": require("./configs/es2017"),
    "es2018": require("./configs/es2018"),
    "es2019": require("./configs/es2019"),
    "es5": require("./configs/es5"),
    "legos3": require("./configs/legos3"),
}
