/**
 * DON'T EDIT THIS FILE WHICH WAS GENERATED BY './scripts/generate-rules.js'.
 */
'use strict';

module.exports = Object.assign(
  require('./foreign-rules/angular'),
  require('./foreign-rules/eslint-comments'),
  require('./foreign-rules/eslint-plugin'),
  require('./foreign-rules/node'),
  require('./foreign-rules/ts'),
  {
    'array-bracket-even-spacing': require('./rules/array-bracket-even-spacing'),
    'arrow-parens': require('./rules/arrow-parens'),
    'block-scoped-var': require('./rules/block-scoped-var'),
    'computed-property-even-spacing': require('./rules/computed-property-even-spacing'),
    'no-callback-literal': require('./rules/no-callback-literal'),
    'no-instanceof-array': require('./rules/no-instanceof-array'),
    'no-instanceof-wrapper': require('./rules/no-instanceof-wrapper'),
    'no-literal-call': require('./rules/no-literal-call'),
    'no-this-in-static': require('./rules/no-this-in-static'),
    'no-use-ignored-vars': require('./rules/no-use-ignored-vars'),
    'no-useless-rest-spread': require('./rules/no-useless-rest-spread'),
    'object-curly-even-spacing': require('./rules/object-curly-even-spacing'),
    'prefer-for-of': require('./rules/prefer-for-of')
  }
);
